{{- if .Values.secret.adminToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attestation.secretName" . }}
  labels:
    {{- include "attestation.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.secret.adminToken | quote }}
{{- end }}
