"""Seed demo data into the SQLite database for the web interface."""
from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

# Add attestation service to path
attestation_src = Path(__file__).parent.parent
if str(attestation_src) not in sys.path:
    sys.path.insert(0, str(attestation_src))

from sqlmodel import Session, SQLModel, create_engine

from sdk.models import AuditLogRow, MachineRow, MachineStatus, NodeRole
from sdk.repositories import AuditRepository, SqlMachineRepository
from core.config import get_settings


def seed_machines(repo: SqlMachineRepository) -> list[MachineRow]:
    """Create demo machine records."""
    now = datetime.now(timezone.utc)
    
    machines = [
        MachineRow(
            machine_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            ek_fingerprint="SHA384:1a2b3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12",
            ek_source="tpm",
            hw_uuid="12345678-1234-1234-1234-123456789012",
            hw_mac="00:11:22:33:44:55",
            hw_serial="SN123456789",
            hw_product="Dell PowerEdge R640",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp-node-01",
            assigned_ip="10.10.0.101",
            config_token="tok-cp-01-abcdef123456",
            token_consumed=True,
            registered_at=now - timedelta(days=7),
            attested_at=now - timedelta(days=7, hours=2),
        ),
        MachineRow(
            machine_id="b2c3d4e5-f6a7-8901-bcde-f12345678901",
            ek_fingerprint="SHA384:2b3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123",
            ek_source="tpm",
            hw_uuid="23456789-2345-2345-2345-234567890123",
            hw_mac="00:11:22:33:44:66",
            hw_serial="SN234567890",
            hw_product="Dell PowerEdge R640",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp-node-02",
            assigned_ip="10.10.0.102",
            config_token="tok-cp-02-bcdef1234567",
            token_consumed=True,
            registered_at=now - timedelta(days=7),
            attested_at=now - timedelta(days=7, hours=2),
        ),
        MachineRow(
            machine_id="c3d4e5f6-a7b8-9012-cdef-123456789012",
            ek_fingerprint="SHA384:3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234",
            ek_source="tpm",
            hw_uuid="34567890-3456-3456-3456-345678901234",
            hw_mac="00:11:22:33:44:77",
            hw_serial="SN345678901",
            hw_product="Dell PowerEdge R740",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker-infra-01",
            assigned_ip="10.10.1.101",
            config_token="tok-wi-01-cdef12345678",
            token_consumed=True,
            registered_at=now - timedelta(days=6),
            attested_at=now - timedelta(days=6, hours=1),
        ),
        MachineRow(
            machine_id="d4e5f6a7-b8c9-0123-def1-234567890123",
            ek_fingerprint="SHA384:4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345",
            ek_source="tpm",
            hw_uuid="45678901-4567-4567-4567-456789012345",
            hw_mac="00:11:22:33:44:88",
            hw_serial="SN456789012",
            hw_product="Dell PowerEdge R740",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker-infra-02",
            assigned_ip="10.10.1.102",
            config_token="tok-wi-02-def123456789",
            token_consumed=True,
            registered_at=now - timedelta(days=6),
            attested_at=now - timedelta(days=6, hours=1),
        ),
        MachineRow(
            machine_id="e5f6a7b8-c9d0-1234-ef12-345678901234",
            ek_fingerprint="SHA384:5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456",
            ek_source="tpm",
            hw_uuid="56789012-5678-5678-5678-567890123456",
            hw_mac="00:11:22:33:44:99",
            hw_serial="SN567890123",
            hw_product="HPE ProLiant DL360 Gen10",
            role=NodeRole.worker_app,
            status=MachineStatus.registered,
            hostname="worker-app-01",
            assigned_ip="10.10.2.101",
            config_token="tok-wa-01-ef1234567890",
            token_consumed=True,
            registered_at=now - timedelta(days=2),
        ),
        MachineRow(
            machine_id="f6a7b8c9-d0e1-2345-f123-456789012345",
            ek_fingerprint="SHA384:6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567",
            ek_source="tpm",
            hw_uuid="67890123-6789-6789-6789-678901234567",
            hw_mac="00:11:22:33:44:aa",
            hw_serial="SN678901234",
            hw_product="HPE ProLiant DL360 Gen10",
            role=NodeRole.worker_app,
            status=MachineStatus.pending_approval,
            hostname="worker-app-02",
            assigned_ip=None,
            config_token=None,
            token_consumed=False,
            registered_at=now - timedelta(hours=3),
        ),
        MachineRow(
            machine_id="a7b8c9d0-e1f2-3456-1234-567890123456",
            ek_fingerprint="SHA384:7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678",
            ek_source="tpm",
            hw_uuid="78901234-7890-7890-7890-789012345678",
            hw_mac="00:11:22:33:44:bb",
            hw_serial="SN789012345",
            hw_product="Dell PowerEdge R650",
            role=NodeRole.worker_app,
            status=MachineStatus.pending_approval,
            hostname="worker-app-03",
            assigned_ip=None,
            config_token=None,
            token_consumed=False,
            registered_at=now - timedelta(hours=1),
        ),
        MachineRow(
            machine_id="b8c9d0e1-f2a3-4567-2345-678901234567",
            ek_fingerprint="SHA384:890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789",
            ek_source="tpm",
            hw_uuid="89012345-8901-8901-8901-890123456789",
            hw_mac="00:11:22:33:44:cc",
            hw_serial="SN890123456",
            hw_product="HPE ProLiant DL380 Gen10",
            role=NodeRole.worker_infra,
            status=MachineStatus.locked,
            hostname="worker-infra-03",
            assigned_ip="10.10.1.103",
            config_token="tok-wi-03-a1b2c3d4e5f6",
            token_consumed=True,
            registered_at=now - timedelta(days=10),
            attested_at=now - timedelta(days=10, hours=2),
            locked_at=now - timedelta(hours=12),
        ),
        # === Cluster 1 (talos-prod-01) - Additional nodes ===
        MachineRow(
            machine_id="c9d0e1f2-a3b4-5678-3456-789012345678",
            ek_fingerprint="SHA384:90abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
            ek_source="tpm",
            hw_uuid="90123456-9012-9012-9012-901234567890",
            hw_mac="00:11:22:33:44:dd",
            hw_serial="SN901234567",
            hw_product="Dell PowerEdge R640",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp-node-03",
            assigned_ip="10.10.0.103",
            config_token="tok-cp-03-f1a2b3c4d5e6",
            token_consumed=True,
            registered_at=now - timedelta(days=6, hours=12),
            attested_at=now - timedelta(days=6, hours=10),
        ),
        MachineRow(
            machine_id="d0e1f2a3-b4c5-6789-4567-890123456789",
            ek_fingerprint="SHA384:0abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901",
            ek_source="tpm",
            hw_uuid="01234567-0123-0123-0123-012345678901",
            hw_mac="00:11:22:33:44:ee",
            hw_serial="SN012345678",
            hw_product="HPE ProLiant DL360 Gen10",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker-infra-04",
            assigned_ip="10.10.1.104",
            config_token="tok-wi-04-a2b3c4d5e6f7",
            token_consumed=True,
            registered_at=now - timedelta(days=5, hours=8),
            attested_at=now - timedelta(days=5, hours=7),
        ),
        MachineRow(
            machine_id="e1f2a3b4-c5d6-7890-5678-901234567890",
            ek_fingerprint="SHA384:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012",
            ek_source="tpm",
            hw_uuid="12345678-1234-1234-1234-123456789013",
            hw_mac="00:11:22:33:44:ff",
            hw_serial="SN123456780",
            hw_product="Dell PowerEdge R740",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker-app-04",
            assigned_ip="10.10.2.102",
            config_token="tok-wa-04-b3c4d5e6f7a8",
            token_consumed=True,
            registered_at=now - timedelta(days=4, hours=6),
            attested_at=now - timedelta(days=4, hours=5),
        ),
        MachineRow(
            machine_id="f2a3b4c5-d6e7-8901-6789-012345678901",
            ek_fingerprint="SHA384:bcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123",
            ek_source="tpm",
            hw_uuid="23456789-2345-2345-2345-234567890124",
            hw_mac="00:11:22:33:55:00",
            hw_serial="SN234567891",
            hw_product="Dell PowerEdge R740",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker-app-05",
            assigned_ip="10.10.2.103",
            config_token="tok-wa-05-c4d5e6f7a8b9",
            token_consumed=True,
            registered_at=now - timedelta(days=4, hours=4),
            attested_at=now - timedelta(days=4, hours=3),
        ),
        MachineRow(
            machine_id="a3b4c5d6-e7f8-9012-7890-123456789012",
            ek_fingerprint="SHA384:cdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234",
            ek_source="tpm",
            hw_uuid="34567890-3456-3456-3456-345678901235",
            hw_mac="00:11:22:33:55:11",
            hw_serial="SN345678902",
            hw_product="HPE ProLiant DL380 Gen10",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker-app-06",
            assigned_ip="10.10.2.104",
            config_token="tok-wa-06-d5e6f7a8b9c0",
            token_consumed=True,
            registered_at=now - timedelta(days=3, hours=10),
            attested_at=now - timedelta(days=3, hours=9),
        ),
        # === Cluster 2 (talos-prod-02) - Full cluster deployment ===
        MachineRow(
            machine_id="b4c5d6e7-f8a9-0123-8901-234567890123",
            ek_fingerprint="SHA384:def1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012345",
            ek_source="tpm",
            hw_uuid="45678901-4567-4567-4567-456789012346",
            hw_mac="00:11:22:44:00:00",
            hw_serial="SN456789013",
            hw_product="Dell PowerEdge R650",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp2-node-01",
            assigned_ip="10.20.0.101",
            config_token="tok-cp2-01-e6f7a8b9c0d1",
            token_consumed=True,
            registered_at=now - timedelta(days=5),
            attested_at=now - timedelta(days=5, hours=-2),
        ),
        MachineRow(
            machine_id="c5d6e7f8-a9b0-1234-9012-345678901234",
            ek_fingerprint="SHA384:ef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456",
            ek_source="tpm",
            hw_uuid="56789012-5678-5678-5678-567890123457",
            hw_mac="00:11:22:44:00:11",
            hw_serial="SN567890124",
            hw_product="Dell PowerEdge R650",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp2-node-02",
            assigned_ip="10.20.0.102",
            config_token="tok-cp2-02-f7a8b9c0d1e2",
            token_consumed=True,
            registered_at=now - timedelta(days=5),
            attested_at=now - timedelta(days=5, hours=-2),
        ),
        MachineRow(
            machine_id="d6e7f8a9-b0c1-2345-0123-456789012345",
            ek_fingerprint="SHA384:f1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234567",
            ek_source="tpm",
            hw_uuid="67890123-6789-6789-6789-678901234568",
            hw_mac="00:11:22:44:00:22",
            hw_serial="SN678901235",
            hw_product="Dell PowerEdge R650",
            role=NodeRole.controlplane,
            status=MachineStatus.attested,
            hostname="cp2-node-03",
            assigned_ip="10.20.0.103",
            config_token="tok-cp2-03-a8b9c0d1e2f3",
            token_consumed=True,
            registered_at=now - timedelta(days=5),
            attested_at=now - timedelta(days=5, hours=-2),
        ),
        MachineRow(
            machine_id="e7f8a9b0-c1d2-3456-1234-567890123456",
            ek_fingerprint="SHA384:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012345678",
            ek_source="tpm",
            hw_uuid="78901234-7890-7890-7890-789012345679",
            hw_mac="00:11:22:44:11:00",
            hw_serial="SN789012346",
            hw_product="HPE ProLiant DL360 Gen11",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker2-infra-01",
            assigned_ip="10.20.1.101",
            config_token="tok-w2i-01-b9c0d1e2f3a4",
            token_consumed=True,
            registered_at=now - timedelta(days=4, hours=18),
            attested_at=now - timedelta(days=4, hours=17),
        ),
        MachineRow(
            machine_id="f8a9b0c1-d2e3-4567-2345-678901234567",
            ek_fingerprint="SHA384:234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456789",
            ek_source="tpm",
            hw_uuid="89012345-8901-8901-8901-890123456780",
            hw_mac="00:11:22:44:11:11",
            hw_serial="SN890123457",
            hw_product="HPE ProLiant DL360 Gen11",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker2-infra-02",
            assigned_ip="10.20.1.102",
            config_token="tok-w2i-02-c0d1e2f3a4b5",
            token_consumed=True,
            registered_at=now - timedelta(days=4, hours=18),
            attested_at=now - timedelta(days=4, hours=17),
        ),
        MachineRow(
            machine_id="a9b0c1d2-e3f4-5678-3456-789012345678",
            ek_fingerprint="SHA384:34567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234567890",
            ek_source="tpm",
            hw_uuid="90123456-9012-9012-9012-901234567891",
            hw_mac="00:11:22:44:11:22",
            hw_serial="SN901234568",
            hw_product="HPE ProLiant DL380 Gen11",
            role=NodeRole.worker_infra,
            status=MachineStatus.attested,
            hostname="worker2-infra-03",
            assigned_ip="10.20.1.103",
            config_token="tok-w2i-03-d1e2f3a4b5c6",
            token_consumed=True,
            registered_at=now - timedelta(days=4, hours=16),
            attested_at=now - timedelta(days=4, hours=15),
        ),
        MachineRow(
            machine_id="b0c1d2e3-f4a5-6789-4567-890123456789",
            ek_fingerprint="SHA384:4567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012345678901",
            ek_source="tpm",
            hw_uuid="01234567-0123-0123-0123-012345678902",
            hw_mac="00:11:22:44:22:00",
            hw_serial="SN012345679",
            hw_product="Dell PowerEdge R750",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker2-app-01",
            assigned_ip="10.20.2.101",
            config_token="tok-w2a-01-e2f3a4b5c6d7",
            token_consumed=True,
            registered_at=now - timedelta(days=3, hours=14),
            attested_at=now - timedelta(days=3, hours=13),
        ),
        MachineRow(
            machine_id="c1d2e3f4-a5b6-7890-5678-901234567890",
            ek_fingerprint="SHA384:567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456789012",
            ek_source="tpm",
            hw_uuid="12345678-1234-1234-1234-123456789014",
            hw_mac="00:11:22:44:22:11",
            hw_serial="SN123456781",
            hw_product="Dell PowerEdge R750",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker2-app-02",
            assigned_ip="10.20.2.102",
            config_token="tok-w2a-02-f3a4b5c6d7e8",
            token_consumed=True,
            registered_at=now - timedelta(days=3, hours=14),
            attested_at=now - timedelta(days=3, hours=13),
        ),
        MachineRow(
            machine_id="d2e3f4a5-b6c7-8901-6789-012345678901",
            ek_fingerprint="SHA384:67890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234567890123",
            ek_source="tpm",
            hw_uuid="23456789-2345-2345-2345-234567890125",
            hw_mac="00:11:22:44:22:22",
            hw_serial="SN234567892",
            hw_product="HPE ProLiant DL380 Gen11",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker2-app-03",
            assigned_ip="10.20.2.103",
            config_token="tok-w2a-03-a4b5c6d7e8f9",
            token_consumed=True,
            registered_at=now - timedelta(days=3, hours=12),
            attested_at=now - timedelta(days=3, hours=11),
        ),
        MachineRow(
            machine_id="e3f4a5b6-c7d8-9012-7890-123456789012",
            ek_fingerprint="SHA384:7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012345678901234",
            ek_source="tpm",
            hw_uuid="34567890-3456-3456-3456-345678901236",
            hw_mac="00:11:22:44:22:33",
            hw_serial="SN345678903",
            hw_product="Dell PowerEdge R750",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker2-app-04",
            assigned_ip="10.20.2.104",
            config_token="tok-w2a-04-b5c6d7e8f9a0",
            token_consumed=True,
            registered_at=now - timedelta(days=2, hours=20),
            attested_at=now - timedelta(days=2, hours=19),
        ),
        MachineRow(
            machine_id="f4a5b6c7-d8e9-0123-8901-234567890123",
            ek_fingerprint="SHA384:890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456789012345",
            ek_source="tpm",
            hw_uuid="45678901-4567-4567-4567-456789012347",
            hw_mac="00:11:22:44:33:00",
            hw_serial="SN456789014",
            hw_product="HPE ProLiant DL360 Gen11",
            role=NodeRole.worker_app,
            status=MachineStatus.attested,
            hostname="worker2-app-05",
            assigned_ip="10.20.2.105",
            config_token="tok-w2a-05-c6d7e8f9a0b1",
            token_consumed=True,
            registered_at=now - timedelta(days=2, hours=18),
            attested_at=now - timedelta(days=2, hours=17),
        ),
        # === New pending/registered nodes ===
        MachineRow(
            machine_id="a5b6c7d8-e9f0-1234-9012-345678901234",
            ek_fingerprint="SHA384:90abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234567890123456",
            ek_source="tpm",
            hw_uuid="56789012-5678-5678-5678-567890123458",
            hw_mac="00:11:22:44:33:11",
            hw_serial="SN567890125",
            hw_product="Dell PowerEdge R750",
            role=NodeRole.worker_app,
            status=MachineStatus.registered,
            hostname="worker-app-07",
            assigned_ip="10.10.2.105",
            config_token="tok-wa-07-d7e8f9a0b1c2",
            token_consumed=True,
            registered_at=now - timedelta(hours=18),
        ),
        MachineRow(
            machine_id="b6c7d8e9-f0a1-2345-0123-456789012345",
            ek_fingerprint="SHA384:0abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012345678901234567",
            ek_source="tpm",
            hw_uuid="67890123-6789-6789-6789-678901234569",
            hw_mac="00:11:22:44:33:22",
            hw_serial="SN678901236",
            hw_product="HPE ProLiant DL380 Gen11",
            role=NodeRole.worker_app,
            status=MachineStatus.pending_approval,
            hostname="worker2-app-06",
            assigned_ip=None,
            config_token=None,
            token_consumed=False,
            registered_at=now - timedelta(hours=8),
        ),
        MachineRow(
            machine_id="c7d8e9f0-a1b2-3456-1234-567890123456",
            ek_fingerprint="SHA384:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456789012345678",
            ek_source="tpm",
            hw_uuid="78901234-7890-7890-7890-789012345680",
            hw_mac="00:11:22:44:33:33",
            hw_serial="SN789012347",
            hw_product="Dell PowerEdge R650",
            role=NodeRole.worker_infra,
            status=MachineStatus.pending_approval,
            hostname="worker-infra-05",
            assigned_ip=None,
            config_token=None,
            token_consumed=False,
            registered_at=now - timedelta(hours=4),
        ),
    ]
    
    saved_machines = []
    for machine in machines:
        saved = repo.save(machine)
        saved_machines.append(saved)
        print(f"✓ Created machine: {machine.hostname} ({machine.status.value})")
    
    return saved_machines


def seed_audit_logs(repo: AuditRepository, machines: list[MachineRow]) -> None:
    """Create demo audit log entries."""
    now = datetime.now(timezone.utc)
    
    entries = [
        # Control plane registrations (7 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=0, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[0].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=0, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[0].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[0].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=0, minutes=8),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[1].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=0, minutes=12),
            operator_cn="admin",
            action="approve",
            machine_id=machines[1].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=7, hours=2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[1].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # Worker infrastructure nodes (6 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=0, minutes=15),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[2].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=0, minutes=20),
            operator_cn="admin",
            action="approve",
            machine_id=machines[2].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=1),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[2].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=0, minutes=18),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[3].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=0, minutes=22),
            operator_cn="admin",
            action="approve",
            machine_id=machines[3].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=1),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[3].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # Recent worker app node (2 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=0, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[4].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=0, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[4].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        # Pending approvals (recent)
        AuditLogRow(
            timestamp=now - timedelta(hours=3),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[5].machine_id,
            prev_state=None,
            new_state="pending_approval",
            detail="Awaiting administrator approval",
        ),
        AuditLogRow(
            timestamp=now - timedelta(hours=1),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[6].machine_id,
            prev_state=None,
            new_state="pending_approval",
            detail="Awaiting administrator approval",
        ),
        # Locked node events (10 days ago + recent lock)
        AuditLogRow(
            timestamp=now - timedelta(days=10, hours=0, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[7].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=10, hours=0, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[7].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=10, hours=2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[7].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        AuditLogRow(
            timestamp=now - timedelta(hours=12),
            operator_cn="security-team",
            action="lock",
            machine_id=machines[7].machine_id,
            prev_state="attested",
            new_state="locked",
            detail="Locked pending security investigation",
        ),
        # === Cluster 1 additional nodes ===
        # cp-node-03 (6.5 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=12, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[8].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=12, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[8].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=6, hours=10),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[8].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker-infra-04 (5 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=8, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[9].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=8, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[9].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=7),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[9].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker-app-04 (4 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=6, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[10].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=6, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[10].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=5),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[10].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker-app-05 (4 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=4, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[11].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=4, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[11].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=3),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[11].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker-app-06 (3 days ago)
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=10, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[12].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=10, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[12].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=9),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[12].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # === Cluster 2 (talos-prod-02) control plane nodes (5 days ago) ===
        # cp2-node-01
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[13].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[13].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=-2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[13].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # cp2-node-02
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=8),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[14].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=12),
            operator_cn="admin",
            action="approve",
            machine_id=machines[14].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=-2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[14].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # cp2-node-03
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=11),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[15].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=0, minutes=15),
            operator_cn="admin",
            action="approve",
            machine_id=machines[15].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=5, hours=-2),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[15].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # === Cluster 2 infrastructure nodes ===
        # worker2-infra-01
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=18, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[16].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=18, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[16].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=17),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[16].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-infra-02
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=18, minutes=8),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[17].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=18, minutes=12),
            operator_cn="admin",
            action="approve",
            machine_id=machines[17].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=17),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[17].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-infra-03
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=16, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[18].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=16, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[18].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=4, hours=15),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[18].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # === Cluster 2 application nodes ===
        # worker2-app-01
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=14, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[19].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=14, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[19].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=13),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[19].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-app-02
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=14, minutes=8),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[20].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=14, minutes=12),
            operator_cn="admin",
            action="approve",
            machine_id=machines[20].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=13),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[20].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-app-03
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=12, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[21].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=12, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[21].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=3, hours=11),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[21].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-app-04
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=20, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[22].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=20, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[22].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=19),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[22].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # worker2-app-05
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=18, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[23].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP - Cluster 2",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=18, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[23].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        AuditLogRow(
            timestamp=now - timedelta(days=2, hours=17),
            operator_cn="SYSTEM",
            action="attest",
            machine_id=machines[23].machine_id,
            prev_state="registered",
            new_state="attested",
            detail="TPM attestation successful",
        ),
        # === Recent registrations (not yet attested) ===
        # worker-app-07 (registered, approved)
        AuditLogRow(
            timestamp=now - timedelta(hours=18, minutes=5),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[24].machine_id,
            prev_state=None,
            new_state="registered",
            detail="Initial registration via ZTP",
        ),
        AuditLogRow(
            timestamp=now - timedelta(hours=18, minutes=10),
            operator_cn="admin",
            action="approve",
            machine_id=machines[24].machine_id,
            prev_state="registered",
            new_state="registered",
            detail="Approved by cluster administrator",
        ),
        # worker2-app-06 (pending approval)
        AuditLogRow(
            timestamp=now - timedelta(hours=8),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[25].machine_id,
            prev_state=None,
            new_state="pending_approval",
            detail="Initial registration via ZTP - Cluster 2 - Awaiting approval",
        ),
        # worker-infra-05 (pending approval)
        AuditLogRow(
            timestamp=now - timedelta(hours=4),
            operator_cn="SYSTEM",
            action="register",
            machine_id=machines[26].machine_id,
            prev_state=None,
            new_state="pending_approval",
            detail="Initial registration via ZTP - Awaiting approval",
        ),
    ]
    
    for entry in entries:
        repo.append(entry)
        print(f"✓ Created audit log: {entry.action} on {entry.machine_id[:8]}... by {entry.operator_cn}")


def main():
    """Seed demo data into the database."""
    print("🌱 Seeding demo data...\n")
    
    settings = get_settings()
    engine = create_engine(
        settings.db_url,
        connect_args={"check_same_thread": False},
    )
    
    # Create all tables
    SQLModel.metadata.create_all(engine)
    print("✓ Created database tables\n")
    
    with Session(engine) as session:
        machine_repo = SqlMachineRepository(session)
        audit_repo = AuditRepository(session)
        
        # Seed machines
        print("📦 Creating machines...")
        machines = seed_machines(machine_repo)
        print(f"✅ Created {len(machines)} machines\n")
        
        # Seed audit logs
        print("📋 Creating audit logs...")
        seed_audit_logs(audit_repo, machines)
        print(f"✅ Created audit log entries\n")
        
        print("🎉 Demo data seeded successfully!")
        print(f"   Database: {settings.db_url}")
        print(f"   Machines: {len(machines)}")
        print(f"   - Attested: {sum(1 for m in machines if m.status == MachineStatus.attested)}")
        print(f"   - Registered: {sum(1 for m in machines if m.status == MachineStatus.registered)}")
        print(f"   - Pending: {sum(1 for m in machines if m.status == MachineStatus.pending_approval)}")
        print(f"   - Locked: {sum(1 for m in machines if m.status == MachineStatus.locked)}")


if __name__ == "__main__":
    main()
